export const AI_RUBROS_GASTOS = [
  { id: 'alquiler', label: 'Alquiler / Expensas' },
  { id: 'servicios', label: 'Servicios (Luz, agua, gas)' },
  { id: 'telefonia', label: 'Internet y Telefonía' },
  { id: 'sueldos', label: 'Sueldos y jornales' },
  { id: 'mercaderia', label: 'Compra de mercadería / insumos' },
  { id: 'transporte', label: 'Transporte y viajes' },
  { id: 'combustible', label: 'Combustible y Lubricantes' },
  { id: 'salud', label: 'Salud y Farmacia' },
  { id: 'educacion', label: 'Educación' },
  { id: 'impuestos', label: 'Impuestos y Tasas' },
  { id: 'seguros', label: 'Seguros' },
  { id: 'reparaciones', label: 'Mantenimiento y reparaciones' },
  { id: 'ocio', label: 'Entretenimiento y Ocio' },
  { id: 'bancos', label: 'Comisiones bancarias' },
  { id: 'multas', label: 'Multas y Recargos' },
  { id: 'comida', label: 'Alimentación' },
  { id: 'ropa', label: 'Ropa / Vestimenta' },
];

export const AI_RUBROS_INGRESOS = [
  { id: 'sueldo_ing', label: 'Sueldos' },
  { id: 'honorarios', label: 'Honorarios profesionales' },
  { id: 'ventas_prod', label: 'Ventas de mercaderías / productos' },
  { id: 'servicios_ing', label: 'Cobros por servicios' },
  { id: 'comisiones_ing', label: 'Comisiones por ventas' },
  { id: 'extraordinarios', label: 'Cobros extraordinarios' },
  { id: 'intereses', label: 'Intereses y Rentas' },
  { id: 'dividendos', label: 'Dividendos' },
  { id: 'bonificaciones', label: 'Bonificaciones / Descuentos recibidos' },
  { id: 'reembolsos', label: 'Reembolso de gastos' },
  { id: 'regalos', label: 'Regalos / Premios' },
  { id: 'subsidios', label: 'Subsidios / Ayudas' },
  { id: 'devoluciones', label: 'Devoluciones de compras' },
  { id: 'activos', label: 'Venta de activos' },
  { id: 'otros_ing', label: 'Cobros varios / Otros' },
];
