export const AI_RUBROS_GASTOS = [
  { id: 'alquiler_expensas', label: 'Alquiler / Expensas' },
  { id: 'servicios_basicos', label: 'Servicios (Luz, agua, gas)' },
  { id: 'internet_telefonia', label: 'Internet y Telefonía' },
  { id: 'sueldos_jornales', label: 'Sueldos y jornales' },
  { id: 'compra_mercaderia', label: 'Compra de mercadería / insumos' },
  { id: 'transporte_viajes', label: 'Transporte y viajes' },
  { id: 'salud_farmacia', label: 'Salud y Farmacia' },
  { id: 'impuestos_tasas', label: 'Impuestos y Tasas' },
  { id: 'mantenimiento_reparaciones', label: 'Mantenimiento y reparaciones' },
  { id: 'entretenimiento_ocio', label: 'Entretenimiento y Ocio' },
  { id: 'comisiones_bancarias', label: 'Comisiones y gastos bancarias' },
  { id: 'alimentacion', label: 'Alimentación' },
  { id: 'ropa_vestimenta', label: 'Ropa / Vestimenta' },
  { id: 'aportes_patronales', label: 'Aportes patronales y personales' },
  { id: 'recreacion', label: 'Actividades de recreación' },
  { id: 'asesoramiento_externo', label: 'Asesoramiento externo' },
  { id: 'publicidad_promociones', label: 'Publicidad y promociones' },
  { id: 'tarjetas_credito', label: 'Tarjetas de créditos' },
  { id: 'viajes_vacaciones', label: 'Viajes y vacaciones' },
  { id: 'distribucion_envios', label: 'Distribución y envíos' },
];

export const AI_RUBROS_INGRESOS = [
  { id: 'salarios_adelantos', label: 'Salarios y adelantos' },
  { id: 'honorarios_profesionales', label: 'Honorarios profesionales' },
  { id: 'ventas_mercaderias', label: 'Ventas de mercaderías / productos' },
  { id: 'cobros_servicios', label: 'Cobros por servicios' },
  { id: 'comisiones_ventas', label: 'Comisiones por ventas' },
  { id: 'cobros_extraordinarios', label: 'Cobros Extraordinarios' },
  { id: 'intereses_rentas', label: 'Intereses y Rentas' },
  { id: 'reembolso_gastos', label: 'Reembolso de gastos' },
  { id: 'regalos_premios', label: 'Regalos y Premios' },
  { id: 'cobros_varios', label: 'Cobros varios y Otros' },
  { id: 'adelantos_clientes', label: 'Adelantos de clientes' },
  { id: 'ahorro_emergencia', label: 'Ahorro de emergencia' },
];
