export const AI_RUBROS_GASTOS = [
  { id: 'alquiler_expensas', label: 'Alquiler / Expensas' },
  { id: 'servicios_basicos', label: 'Servicios (Luz, agua, gas)' },
  { id: 'internet_telefonia', label: 'Internet y Telefonía' },
  { id: 'sueldos_jornales', label: 'Sueldos y jornales' },
  { id: 'compra_mercaderia', label: 'Compra de mercadería / insumos' },
  { id: 'transporte_viajes', label: 'Transporte y viajes' },
  { id: 'combustible_lubricantes', label: 'Combustible y Lubricantes' },
  { id: 'salud_farmacia', label: 'Salud y Farmacia' },
  { id: 'educacion', label: 'Educación' },
  { id: 'impuestos_tasas', label: 'Impuestos y Tasas' },
  { id: 'seguros', label: 'Seguros' },
  { id: 'mantenimiento_reparaciones', label: 'Mantenimiento y reparaciones' },
  { id: 'entretenimiento_ocio', label: 'Entretenimiento y Ocio' },
  { id: 'comisiones_bancarias', label: 'Comisiones y gastos bancarias' },
  { id: 'multas_recargos', label: 'Multas y Recargos' },
  { id: 'alimentacion', label: 'Alimentación' },
  { id: 'ropa_vestimenta', label: 'Ropa / Vestimenta' },
  { id: 'contribuciones', label: 'Contribuciones' },
  { id: 'patentes', label: 'Patentes' },
  { id: 'aportes_patronales', label: 'Aportes patronales y personales' },
  { id: 'gimnasio', label: 'Gimnasio' },
  { id: 'recreacion', label: 'Actividades de recreación' },
  { id: 'asesoramiento_externo', label: 'Asesoramiento externo' },
  { id: 'descuentos_concedidos', label: 'Descuentos concedidos' },
  { id: 'papeleria', label: 'Gastos de papelería' },
  { id: 'regalos_gastos', label: 'Regalos' },
  { id: 'publicidad_promociones', label: 'Publicidad y promociones' },
  { id: 'anticipos_proveedores', label: 'Anticipos a proveedores' },
  { id: 'convenios_varios', label: 'Convenios varios' },
  { id: 'tarjetas_credito', label: 'Tarjetas de créditos' },
  { id: 'prestamos', label: 'Préstamos con instituciones financieras y no financieras' },
  { id: 'hipoteca', label: 'Hipoteca' },
  { id: 'estacionamientos_peajes', label: 'Estacionamientos y peajes' },
  { id: 'viajes_vacaciones', label: 'Viajes y vacaciones' },
  { id: 'distribucion_envios', label: 'Distribución y envíos' },
  { id: 'retiros_bancarios', label: 'Retiros de cuentas bancarias' },
];

export const AI_RUBROS_INGRESOS = [
  { id: 'salarios_adelantos', label: 'Salarios y adelantos' },
  { id: 'honorarios_profesionales', label: 'Honorarios profesionales' },
  { id: 'ventas_mercaderias', label: 'Ventas de mercaderías / productos' },
  { id: 'cobros_servicios', label: 'Cobros por servicios' },
  { id: 'comisiones_ventas', label: 'Comisiones por ventas' },
  { id: 'cobros_extraordinarios', label: 'Cobros Extraordinarios' },
  { id: 'intereses_rentas', label: 'Intereses y Rentas' },
  { id: 'dividendos', label: 'Dividendos' },
  { id: 'bonificaciones_recibidas', label: 'Bonificaciones / Descuentos recibidos' },
  { id: 'reembolso_gastos', label: 'Reembolso de gastos' },
  { id: 'regalos_premios', label: 'Regalos y Premios' },
  { id: 'subsidios_ayudas', label: 'Subsidios y Ayudas' },
  { id: 'devoluciones_compras', label: 'Devoluciones de compras' },
  { id: 'venta_activos', label: 'Venta de activos' },
  { id: 'cobros_varios', label: 'Cobros varios y Otros' },
  { id: 'adelantos_clientes', label: 'Adelantos de clientes' },
  { id: 'ahorro_emergencia', label: 'Ahorro de emergencia' },
];
