const { Client } = require('../server/node_modules/pg');
const io = require('../app/node_modules/socket.io-client');

const dbConfig = {
  host: 'db.peiapp.tech',
  port: 5432,
  database: 'peiapp_dev',
  user: 'db_user_peiapp_dev',
  password: 'Z7mQ4vK9T2rX8pL5nW3s',
};

async function runTest() {
  console.log('--- STARTING INTEGRATION TEST ---');
  
  // 1. Check DB Connection and fetch a ticket and users
  const pgClient = new Client(dbConfig);
  let ticket = null;
  let owner = null;
  let participant = null;
  
  try {
    console.log('Connecting to database...');
    await pgClient.connect();
    console.log('✅ Connected to database successfully.');
    
    // Fetch a ticket that has at least two details (owner + receiver/participant)
    const ticketRes = await pgClient.query(`
      SELECT t.ticket_id, t.description, t.amount, t.owner_id
      FROM tickets t
      LIMIT 1
    `);
    
    if (ticketRes.rows.length === 0) {
      throw new Error('No tickets found in the database. Run the app or insert a ticket first.');
    }
    
    ticket = ticketRes.rows[0];
    console.log(`Found test ticket: ID=${ticket.ticket_id}, Description="${ticket.description}"`);
    
    // Fetch two users from the users table
    const usersRes = await pgClient.query(`
      SELECT user_id, display_name, phone FROM users LIMIT 2
    `);
    
    if (usersRes.rows.length < 2) {
      throw new Error('Not enough users found in the database (need at least 2).');
    }
    
    owner = usersRes.rows[0];
    participant = usersRes.rows[1];
    console.log(`User A (Owner/Sender): ID=${owner.user_id}, Name="${owner.display_name}"`);
    console.log(`User B (Receiver): ID=${participant.user_id}, Name="${participant.display_name}"`);
    
  } catch (err) {
    console.error('❌ Database connection/query failed:', err.message);
    process.exit(1);
  }

  // 2. Connect WebSockets
  console.log('\nConnecting WebSockets to http://localhost:3001...');
  const socketA = io('http://localhost:3001', { transports: ['websocket'] });
  const socketB = io('http://localhost:3001', { transports: ['websocket'] });

  const connectPromise = (socket, name) => new Promise((resolve, reject) => {
    socket.on('connect', () => {
      console.log(`✅ WebSocket Client ${name} connected (ID: ${socket.id}).`);
      resolve();
    });
    socket.on('connect_error', (err) => {
      reject(new Error(`WebSocket Client ${name} failed to connect: ${err.message}`));
    });
  });

  try {
    await Promise.all([
      connectPromise(socketA, 'A'),
      connectPromise(socketB, 'B')
    ]);
  } catch (err) {
    console.error('❌ WebSocket connection failed:', err.message);
    socketA.disconnect();
    socketB.disconnect();
    await pgClient.end();
    process.exit(1);
  }

  // 3. Join Room
  console.log(`\nClients joining room for ticket: ${ticket.ticket_id}...`);
  socketA.emit('joinTicket', ticket.ticket_id);
  socketB.emit('joinTicket', ticket.ticket_id);
  
  // Wait a moment for room join to complete
  await new Promise(r => setTimeout(r, 1000));
  console.log('Clients joined room.');

  // 4. Setup message receiver on Client B
  const messageText = `Test message generated by integration script at ${new Date().toISOString()}`;
  
  const receivePromise = new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      reject(new Error('Timeout: Client B did not receive the newMessage event within 5 seconds.'));
    }, 5000);
    
    socketB.on('newMessage', (data) => {
      console.log('\n📥 Client B received newMessage event:');
      console.log(JSON.stringify(data, null, 2));
      
      if (data.message === messageText && data.ticketId === ticket.ticket_id) {
        clearTimeout(timeout);
        console.log('✅ Received message matches sent message and ticket ID.');
        resolve(data);
      } else {
        console.log('⚠️ Received message did not match expected content, continuing to wait...');
      }
    });
  });

  // 5. Send message from Client A
  console.log(`\n📤 Client A sending message: "${messageText}"...`);
  socketA.emit('sendMessage', {
    ticketId: ticket.ticket_id,
    senderId: owner.user_id,
    message: messageText,
    senderName: owner.display_name
  });

  try {
    const receivedData = await receivePromise;
    console.log('✅ WebSocket communication verified successfully.');
    
    // 6. Verify Database Persistence
    console.log('\nVerifying message persistence in PostgreSQL...');
    // Wait a brief moment for async db write in wss-server to finish
    await new Promise(r => setTimeout(r, 1500));
    
    const dbCheckRes = await pgClient.query(`
      SELECT chat_id, ticket_id, sender_id, message, sender_name, created_at
      FROM ticket_chat
      WHERE chat_id = $1
    `, [receivedData.chatId]);
    
    if (dbCheckRes.rows.length > 0) {
      const dbRow = dbCheckRes.rows[0];
      console.log('✅ Message found in PostgreSQL:');
      console.log(JSON.stringify(dbRow, null, 2));
      
      // Clean up the test message from the database
      console.log('\nCleaning up integration test message from DB...');
      await pgClient.query('DELETE FROM ticket_chat WHERE chat_id = $1', [receivedData.chatId]);
      console.log('✅ Cleaned up test message successfully.');
    } else {
      console.error('❌ Message not found in database. Check wss-server logs.');
    }
    
  } catch (err) {
    console.error('❌ Test failed:', err.message);
  } finally {
    socketA.disconnect();
    socketB.disconnect();
    await pgClient.end();
    console.log('\n--- INTEGRATION TEST CONCLUDED ---');
  }
}

runTest();
